print("Hello", end = "-")
print("World", end = "")
print("!")
print(1, 2, 3, 4, 5, end = "===")
print(1, 2, 3, 4, 5, sep = ':', end = "===")
print(1, 2, 3, 4, 5, sep = ',')
print("print function is awesome")